### PR TITLE
Migrating links from Trello

### PR DESCRIPTION
**Pull request by mirekdlugosz**
@omaciel I need your help in finishing files in commit 9715f762b4e4743f0fe441892752dae63be3cc59 . Some links are missing tags, all miss submitter URL and some miss excerpt. linter will fail until these issues are fixed.

I tried adding tags to some links, I'd appreciate if you review that (and feel free to change).

I would also consider dropping some of links. Like the one about npm package breaking JS ecosystem - it's news, and at this point it's old news.

Whenever you do any changes, feel free to amend to last commit and force-push. I would like to keep this PR at two commits - one for links added by me, one for links added by you.

### CODE REVIEW

**Comment by omaciel** [comment]
Hi @mirekdlugosz so basically add the missing information for the files already included in this PR?

**Comment by mirekdlugosz** [comment]
@omaciel yes :)

**Comment by mirekdlugosz** [comment]
@omaciel looks it's all green. I can squash all your commits and force-push, so we can merge. sounds ok?

**Comment by omaciel** [comment]
> @omaciel looks it's all green. I can squash all your commits and force-push, so we can merge. sounds ok?

ack

**Pull request merged**
